"use client";
import { useRef, useState } from "react";
import { Download, Share2, TrendingUp, Flame, Brain } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { TAG_LABELS, MOOD_CONFIG } from "@/lib/mood-utils";
import type { WellnessSummary } from "@/types";
import { format } from "date-fns";

interface Props { summary: WellnessSummary; }

export default function WellnessSummaryExport({ summary }: Props) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [copying, setCopying] = useState(false);

  const moodLabel = MOOD_CONFIG[Math.round(summary.averageMood) as 1|2|3|4|5]?.label ?? "Moderate";
  const moodColor = MOOD_CONFIG[Math.round(summary.averageMood) as 1|2|3|4|5]?.color ?? "#6b7280";

  const handleCopyText = async () => {
    setCopying(true);
    const text = [
      "ExamMind Wellness Summary",
      `Generated: ${format(new Date(summary.generatedAt), "MMM d, yyyy")}`,
      `Period: Last ${summary.periodDays} check-ins`,
      `Average Mood: ${summary.averageMood.toFixed(1)}/5 (${moodLabel})`,
      `Check-in Streak: ${summary.streakData.currentStreak} days`,
      `Top Stress Areas: ${summary.topTriggers.map(t => TAG_LABELS[t.tag as keyof typeof TAG_LABELS] ?? t.tag).join(", ")}`,
      `Weekly Insight: ${summary.weeklyInsight}`,
      "",
      "NOTE: Raw journal entries are NOT included. This summary contains aggregate trends only.",
    ].join("\n");
    await navigator.clipboard.writeText(text);
    setTimeout(() => setCopying(false), 2000);
  };

  return (
    <div className="space-y-4">
      <p className="text-sm text-muted-foreground bg-amber-50 border border-amber-200 rounded-lg px-3 py-2">
        <strong>Privacy note:</strong> This summary contains only aggregate mood trends and stress themes — never raw journal text.
      </p>

      <div ref={cardRef} className="bg-white border-2 border-violet-200 rounded-2xl p-6 space-y-5">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold text-violet-800">ExamMind Wellness Report</h2>
            <p className="text-xs text-muted-foreground">{format(new Date(summary.generatedAt), "MMMM d, yyyy")} · Last {summary.periodDays} check-ins</p>
          </div>
          <div className="text-3xl" aria-hidden="true">🧘</div>
        </div>

        <div className="grid grid-cols-3 gap-3">
          <div className="bg-violet-50 rounded-xl p-3 text-center">
            <p className="text-2xl font-bold" style={{ color: moodColor }}>{summary.averageMood.toFixed(1)}</p>
            <p className="text-xs text-muted-foreground">Avg Mood / 5</p>
            <p className="text-xs font-medium mt-0.5" style={{ color: moodColor }}>{moodLabel}</p>
          </div>
          <div className="bg-orange-50 rounded-xl p-3 text-center">
            <div className="flex items-center justify-center gap-1">
              <Flame className="h-5 w-5 text-orange-400" aria-hidden="true" />
              <p className="text-2xl font-bold text-orange-700">{summary.streakData.currentStreak}</p>
            </div>
            <p className="text-xs text-muted-foreground">Day Streak</p>
          </div>
          <div className="bg-green-50 rounded-xl p-3 text-center">
            <p className="text-2xl font-bold text-green-700">{summary.streakData.totalCheckIns}</p>
            <p className="text-xs text-muted-foreground">Total Check-ins</p>
          </div>
        </div>

        {summary.topTriggers.length > 0 && (
          <div>
            <div className="flex items-center gap-1.5 mb-2">
              <TrendingUp className="h-4 w-4 text-violet-500" aria-hidden="true" />
              <p className="text-sm font-medium">Top Stress Areas (this period)</p>
            </div>
            <div className="flex flex-wrap gap-2">
              {summary.topTriggers.map((t, i) => (
                <Badge key={t.tag} variant={i === 0 ? "default" : "secondary"} className="text-xs">
                  {TAG_LABELS[t.tag as keyof typeof TAG_LABELS] ?? t.tag} · {t.count}x
                </Badge>
              ))}
            </div>
          </div>
        )}

        {summary.weeklyInsight && (
          <div className="bg-violet-50 rounded-xl p-3">
            <div className="flex items-center gap-1.5 mb-1">
              <Brain className="h-4 w-4 text-violet-500" aria-hidden="true" />
              <p className="text-xs font-medium text-violet-700 uppercase tracking-wide">Patterns Noticed</p>
            </div>
            <p className="text-sm text-violet-800">{summary.weeklyInsight}</p>
          </div>
        )}

        <p className="text-xs text-muted-foreground text-center border-t pt-3">
          Generated by ExamMind · Raw journal entries not shared · For informational purposes only
        </p>
      </div>

      <div className="flex gap-2">
        <Button onClick={handleCopyText} variant="outline" className="flex-1">
          <Share2 className="h-4 w-4 mr-1.5" aria-hidden="true" />
          {copying ? "Copied!" : "Copy as Text"}
        </Button>
        <Button onClick={() => window.print()} variant="outline" className="flex-1">
          <Download className="h-4 w-4 mr-1.5" aria-hidden="true" />
          Print / Save PDF
        </Button>
      </div>
    </div>
  );
}